export {default as About } from "./About"
export {default as Contact } from "./Contact"
export {default as Footer } from "./Footer"
export {default as Portfolio } from "./Portfolio"
export {default as Header } from "./Header"
export {default as Testimonials } from "./Testimonials"
export {default as Resume} from "./Resume"